# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'coreDataWrapper-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coreDataWrapper-Demo
  pod 'OrkaCoreDataWrapper', :path => '../'

  target 'coreDataWrapper-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coreDataWrapper-DemoUITests' do
    # Pods for testing
  end

end
